### PR TITLE
fix odoc

### LINKED ISSUE #751: make odoc fails
```
File "lplib__Filename.cmt":
Failed to compile expansion for include : module type of struct include unresolvedroot(Stdlib).Filename end Unexpanded `module type of` expression: module type of struct include unresolvedroot(Stdlib).Filename end
File "lplib__Array.cmt":
Failed to compile expansion for include : module type of struct include identifier((root Lplib__Array).A, false) end Unexpanded `module type of` expression: module type of struct include identifier((root Lplib__Array).A, false) end
File "lplib__List.cmt":
Failed to compile expansion for include : module type of struct include identifier((root Lplib__List).L, false) end Unexpanded `module type of` expression: module type of struct include identifier((root Lplib__List).L, false) end
File "lplib__String.cmt":
Failed to compile expansion for include : module type of struct include identifier((root Lplib__String).S, false) end Unexpanded `module type of` expression: module type of struct include identifier((root Lplib__String).S, false) end
File "src/core/term.mli", line 384, characters 29-30:
Unpaired ']' (end of code).
Suggestion: try '\]'.
File "core__Term.cmti":
Couldn't find the following modules:
  Stdlib
File "src/core/infer.mli", line 16, characters 55-56:
Unpaired ']' (end of code).
Suggestion: try '\]'.
File "../../src/common/.common.objs/byte/common.odoc":
Couldn't find the following modules:
  Stdlib Timed
File "../../src/common/.common.objs/byte/common.odoc":
Failed to lookup type unresolvedroot(Stdlib__Map).Make(identifier((root Common).Path.Path, false)).t Parent_module: Unresolved apply
File "../../src/common/.common.objs/byte/common.odoc":
Failed to lookup type unresolvedroot(Stdlib__Set).Make(identifier((root Common).Path.Path, false)).t Parent_module: Unresolved apply
File "../../src/handle/.handle.objs/byte/handle.odoc":
Couldn't find the following modules:
  Stdlib Timed Why3
File "src/handle/compile.ml", line 101, characters 4-30:
Failed to resolve reference unresolvedroot(Command).with_proofs Couldn't find signature "with_proofs"
File "../../src/lsp/.lsp.objs/byte/lsp.odoc":
Couldn't find the following modules:
  Stdlib Yojson
File "../../src/tool/.tool.objs/byte/tool.odoc":
Couldn't find the following modules:
  Stdlib
File "src/tool/tree_graphviz.ml", line 4, characters 39-53:
Failed to resolve reference unresolvedroot(Tree).t Couldn't find "Tree"
File "../../src/core/.core.objs/byte/core.odoc":
Couldn't find the following modules:
  Bindlib Pratter Stdlib Timed
File "src/core/tree_type.ml", line 152, characters 22-37:
Failed to resolve reference unresolvedroot(capacity) Couldn't find "capacity"
File "src/core/tree_type.ml", line 130, characters 41-55:
Failed to resolve reference unresolvedroot(store) Couldn't find "store"
File "src/core/tree_type.ml", line 119, characters 43-60:
Failed to resolve reference unresolvedroot(children) Couldn't find "children"
File "src/core/tree_type.ml", line 103, characters 42-64:
Failed to resolve reference unresolvedroot(Tree).rule_order Couldn't find signature "rule_order"
File "src/core/tree_type.ml", line 57, characters 4-13:
Failed to resolve reference unresolvedroot(b NOTE) Couldn't find "b NOTE"
File "../../src/core/.core.objs/byte/core.odoc":
Failed to lookup type unresolvedroot(Stdlib__Map).Make(identifier((root Core).Tree_type.TC, false)).t Parent_module: Unresolved apply
File "src/core/tree.ml", line 692, characters 4-21:
Failed to resolve reference unresolvedroot(CM).store Couldn't find "store"
File "src/core/tree.ml", line 687, characters 4-23:
Failed to resolve reference unresolvedroot(rhs_substit) Couldn't find "rhs_substit"
File "src/core/tree.ml", line 179, characters 8-37:
Failed to resolve reference unresolvedroot(Extra).List.reconstruct Couldn't find "Extra"
File "src/core/tree.ml", line 178, characters 52-78:
Failed to resolve reference unresolvedroot(Extra).List.destruct Couldn't find "Extra"
File "src/core/tree.ml", line 175, characters 33-46:
Failed to resolve reference unresolvedroot(stack) Couldn't find "stack"
File "src/core/tree.ml", line 45, characters 34-51:
Failed to resolve reference unresolvedroot(Term).tree Couldn't find "tree"
File "src/core/tree.ml", line 25, characters 4-24:
Failed to resolve reference unresolvedroot(Tree_types) Parent_module: Lookup failure (root module): Tree_types
File "src/core/term.mli", line 5, characters 46-63:
Failed to resolve reference unresolvedroot(Bindlib) Parent_module: Lookup failure (root module): Bindlib
File "src/core/term.mli", line 242, characters 50-67:
Failed to resolve reference unresolvedroot(Terms).sym Couldn't find "Terms"
File "src/core/term.mli", line 208, characters 12-34:
Failed to resolve reference unresolvedroot(term_env array) Couldn't find "term_env array"
File "src/core/term.mli", line 180, characters 54-78:
Failed to resolve reference unresolvedroot(terms).rule.vars Couldn't find "terms"
File "src/core/term.mli", line 180, characters 14-39:
Failed to resolve reference unresolvedroot(terms).rule.xvars Couldn't find "terms"
File "src/core/term.mli", line 177, characters 39-51:
Failed to resolve reference unresolvedroot(Sr) Parent_module: Lookup failure (root module): Sr
File "src/core/term.mli", line 111, characters 11-34:
Failed to resolve reference unresolvedroot(Constant) Couldn't find "Constant"
File "src/core/term.mli", line 82, characters 44-60:
Failed to resolve reference unresolvedroot(sym_prop) Couldn't find "sym_prop"
File "src/core/libTerm.ml", line 11, characters 17-41:
Failed to resolve reference unresolvedroot(Array).map to_tvar Couldn't find "Array"
File "src/core/ctxt.ml", line 94, characters 44-67:
Failed to resolve reference unresolvedroot(LibTerm).get_args Couldn't find signature "get_args"
File "src/core/ctxt.ml", line 67, characters 32-52:
Failed to resolve reference unresolvedroot(Term).unfold t Couldn't find signature "unfold t"
File "../../src/parsing/.parsing.objs/byte/parsing.odoc":
Couldn't find the following modules:
  Bindlib Pratter Sedlexing Stdlib
File "src/parsing/syntax.ml", line 88, characters 22-45:
Failed to resolve reference unresolvedroot(LibTerm).get_args Couldn't find "LibTerm"
File "src/parsing/scope.mli", line 15, characters 13-34:
Failed to resolve reference unresolvedroot(Public) Couldn't find "Public"
File "../../src/lplib/.lplib.objs/byte/lplib.odoc":
Couldn't find the following modules:
  Stdlib Stdlib__Array
File "src/lplib/list.ml", line 161, characters 4-22:
Failed to resolve reference unresolvedroot(deconstruct) Couldn't find "deconstruct"
File "../../src/lplib/.lplib.objs/byte/lplib.odoc":
Failed to lookup type unresolvedroot(Stdlib__Set).Make(unresolvedroot(Lplib).String).t Parent_module: Unresolved apply
File "../../src/lplib/.lplib.objs/byte/lplib.odoc":
Failed to lookup type unresolvedroot(Stdlib__Map).Make(unresolvedroot(Lplib).String).t Parent_module: Unresolved apply
File "../../src/lplib/.lplib.objs/byte/lplib.odoc":
Failed to lookup type unresolvedroot(Stdlib__Set).Make(unresolvedroot(Lplib).Base.Int).t Parent_module: Unresolved apply
File "../../src/lplib/.lplib.objs/byte/lplib.odoc":
Failed to lookup type unresolvedroot(Stdlib__Map).Make(unresolvedroot(Lplib).Base.Int).t Parent_module: Unresolved apply
```

### PR DESCRIPTION
**Pull request by fblanqui**
try to fix #751

### CODE REVIEW

**Comment by fblanqui** [comment]
I still have the following errors:
```
File "lplib__Filename.cmt":
Failed to compile expansion for include : module type of struct include unresolvedroot(Stdlib).Filename end Unexpanded `module type of` expression: module type of struct include unresolvedroot(Stdlib).Filename end
File "lplib__Array.cmt":
Failed to compile expansion for include : module type of struct include identifier((root Lplib__Array).A, false) end Unexpanded `module type of` expression: module type of struct include identifier((root Lplib__Array).A, false) end
File "lplib__List.cmt":
Failed to compile expansion for include : module type of struct include identifier((root Lplib__List).L, false) end Unexpanded `module type of` expression: module type of struct include identifier((root Lplib__List).L, false) end
File "lplib__String.cmt":
Failed to compile expansion for include : module type of struct include identifier((root Lplib__String).S, false) end Unexpanded `module type of` expression: module type of struct include identifier((root Lplib__String).S, false) end
File "core__Term.cmti":
Couldn't find the following modules:
  Stdlib
File "../../src/common/.common.objs/byte/common.odoc":
Couldn't find the following modules:
  Stdlib Timed
File "../../src/common/.common.objs/byte/common.odoc":
Failed to lookup type unresolvedroot(Stdlib__Map).Make(identifier((root Common).Path.Path, false)).t Parent_module: Unresolved apply
File "../../src/common/.common.objs/byte/common.odoc":
Failed to lookup type unresolvedroot(Stdlib__Set).Make(identifier((root Common).Path.Path, false)).t Parent_module: Unresolved apply
File "../../src/handle/.handle.objs/byte/handle.odoc":
Couldn't find the following modules:
  Stdlib Timed Why3
File "../../src/lsp/.lsp.objs/byte/lsp.odoc":
Couldn't find the following modules:
  Stdlib Yojson
File "../../src/tool/.tool.objs/byte/tool.odoc":
Couldn't find the following modules:
  Stdlib
File "../../src/core/.core.objs/byte/core.odoc":
Couldn't find the following modules:
  Bindlib Pratter Stdlib Timed
File "../../src/core/.core.objs/byte/core.odoc":
Failed to lookup type unresolvedroot(Stdlib__Map).Make(identifier((root Core).Tree_type.TC, false)).t Parent_module: Unresolved apply
File "../../src/parsing/.parsing.objs/byte/parsing.odoc":
Couldn't find the following modules:
  Bindlib Pratter Sedlexing Stdlib
File "../../src/lplib/.lplib.objs/byte/lplib.odoc":
Couldn't find the following modules:
  Stdlib Stdlib__Array
File "../../src/lplib/.lplib.objs/byte/lplib.odoc":
Failed to lookup type unresolvedroot(Stdlib__Set).Make(unresolvedroot(Lplib).String).t Parent_module: Unresolved apply
File "../../src/lplib/.lplib.objs/byte/lplib.odoc":
Failed to lookup type unresolvedroot(Stdlib__Map).Make(unresolvedroot(Lplib).String).t Parent_module: Unresolved apply
File "../../src/lplib/.lplib.objs/byte/lplib.odoc":
Failed to lookup type unresolvedroot(Stdlib__Set).Make(unresolvedroot(Lplib).Base.Int).t Parent_module: Unresolved apply
File "../../src/lplib/.lplib.objs/byte/lplib.odoc":
Failed to lookup type unresolvedroot(Stdlib__Map).Make(unresolvedroot(Lplib).Base.Int).t Parent_module: Unresolved apply
```
Does anyone know how to solve them?

**Comment by gabrielhdt** [comment]
It looks like it struggles on cross reference. On the other hand, using [odig](https://opam.ocaml.org/packages/odig/), the documentation looks good, and the cross references are there.
2021-12-01-100758_613x1063_scrot

**Comment by gabrielhdt** [comment]
We can also inline the documentation of included modules, with `@inline`, for instance, in `Filename`, it renders
2021-12-01-100914_653x921_scrot

**Comment by fblanqui** [comment]
@gabrielhdt How do you get those pages with odig?

**Comment by gabrielhdt** [comment]
`odig doc lambdapi`, provided that you have installed odig with opam, and possibly generated the documentation with `odig odoc`

**Comment by fblanqui** [comment]
Ah I see. But why is it written "Package lambdapi 1.0"?
So, do you suggest to replace `@dune build --only-packages lambdapi @doc` by `odig odoc lambdapi`?
Note that the links to README and CHANGES do not work. They perhaps need to be installed too.

**Comment by gabrielhdt** [comment]
I think it grabs some data from the opam file. IMO we can replace the target with `odig doc lambdapi`, since it effectively shows the documentation, which is more useful than generating some doc somewhere in `_build` with errors.

It seems that odig is happy with lambdapi, if one runs `odig odoc lambdapi` then `odig log`, it looks like there is no error and no warning.

**Comment by gabrielhdt** [comment]
> Ah I see. But why is it written "Package lambdapi 1.0"? So, do you suggest to replace `@dune build --only-packages lambdapi @doc` by `odig odoc lambdapi`? Note that the links to README and CHANGES do not work. They perhaps need to be installed too.

which links are you talking about? I can do `odig readme lambdapi` and `odig changes lambdapi`, both work.

**Comment by gabrielhdt** [comment]
> Ah I see. But why is it written "Package lambdapi 1.0"? So, do you suggest to replace `@dune build --only-packages lambdapi @doc` by `odig odoc lambdapi`? Note that the links to README and CHANGES do not work. They perhaps need to be installed too.

In fact, `odig odoc` won't use the local repository, it uses what's installed in opam, so it might not be a good idea to replace the `odoc` target.

**Comment by fblanqui** [comment]
@gabrielhdt So what do you propose?

**Comment by gabrielhdt** [comment]
Maybe we can just remove the target and advise to use odig properly in the documentation?

**Comment by fblanqui** [comment]
Perhaps we could open an issue on odoc to get some help?

**Comment by fblanqui** [comment]
I still have some warnings (see below) but this is the expected behavior at the moment (see https://github.com/ocaml/odoc/issues/794):
```
File "lplib__Filename.cmt":
Warning: Couldn't find the following modules:
  Stdlib
File "lplib__Array.cmt":
Warning: Failed to compile expansion for include : module type of struct include identifier((root Lplib__Array).A, false) end Unexpanded `module type of` expression: module type of struct include identifier((root Lplib__Array).A, false) end
File "lplib__List.cmt":
Warning: Failed to compile expansion for include : module type of struct include identifier((root Lplib__List).L, false) end Unexpanded `module type of` expression: module type of struct include identifier((root Lplib__List).L, false) end
File "lplib__String.cmt":
Warning: Failed to compile expansion for include : module type of struct include identifier((root Lplib__String).S, false) end Unexpanded `module type of` expression: module type of struct include identifier((root Lplib__String).S, false) end
File "core__Term.cmti":
Warning: Couldn't find the following modules:
  Stdlib
File "../../src/common/.common.objs/byte/common.odoc":
Warning: Couldn't find the following modules:
  Stdlib Timed
File "../../src/common/.common.objs/byte/common.odoc":
Warning: Failed to lookup type unresolvedroot(Stdlib__Map).Make(identifier((root Common).Path.Path, false)).t Parent_module: Unresolved apply
File "../../src/common/.common.objs/byte/common.odoc":
Warning: Failed to lookup type unresolvedroot(Stdlib__Set).Make(identifier((root Common).Path.Path, false)).t Parent_module: Unresolved apply
File "../../src/handle/.handle.objs/byte/handle.odoc":
Warning: Couldn't find the following modules:
  Stdlib Timed Why3
File "../../src/lsp/.lsp.objs/byte/lsp.odoc":
Warning: Couldn't find the following modules:
  Stdlib Yojson
File "../../src/tool/.tool.objs/byte/tool.odoc":
Warning: Couldn't find the following modules:
  Stdlib
File "../../src/core/.core.objs/byte/core.odoc":
Warning: Couldn't find the following modules:
  Pratter Stdlib Timed
File "../../src/core/.core.objs/byte/core.odoc":
Warning: Failed to lookup type unresolvedroot(Stdlib__Map).Make(identifier((root Core).Tree_type.TC, false)).t Parent_module: Unresolved apply
File "../../src/lplib/.lplib.objs/byte/lplib.odoc":
Warning: Couldn't find the following modules:
  Stdlib Stdlib__Array
File "../../src/lplib/.lplib.objs/byte/lplib.odoc":
Warning: Failed to lookup type unresolvedroot(Stdlib__Set).Make(unresolvedroot(Lplib).String).t Parent_module: Unresolved apply
File "../../src/lplib/.lplib.objs/byte/lplib.odoc":
Warning: Failed to lookup type unresolvedroot(Stdlib__Map).Make(unresolvedroot(Lplib).String).t Parent_module: Unresolved apply
File "../../src/lplib/.lplib.objs/byte/lplib.odoc":
Warning: Failed to lookup type unresolvedroot(Stdlib__Set).Make(unresolvedroot(Lplib).Base.Int).t Parent_module: Unresolved apply
File "../../src/lplib/.lplib.objs/byte/lplib.odoc":
Warning: Failed to lookup type unresolvedroot(Stdlib__Map).Make(unresolvedroot(Lplib).Base.Int).t Parent_module: Unresolved apply
File "../../src/parsing/.parsing.objs/byte/parsing.odoc":
Warning: Couldn't find the following modules:
  Pratter Sedlexing Stdlib
```

**Pull request merged**
