### PR TITLE
Improve logs

### PR DESCRIPTION
**Pull request by fblanqui**
- add Base.out = Format.fprintf
- uniformize printing code using Base.out
- rename oc arguments into ppf
- complete Term.pp_term
- improve some functions in Debug.D
- improve logging messages in Infer by adding a level argument

### CODE REVIEW

**Comment by yannl35133** [comment]
Pourquoi avoir retiré les noms des loggers dans les logs ?

**Comment by fblanqui** [comment]
I was finding more disadvantages than advantages to keep it. Without, it is less verbose and it is easy to understand from which file it comes anyway.

**Comment by yannl35133** [comment]
I don't find these 7 characters that invasive, and the context is not always sufficient to see easily where they come from.
Maybe the second point is what should be changed, I don't know

**Comment by gabrielhdt** [comment]
I'd be in favour of keeping loggers' names.

**Pull request merged**
