### PR TITLE
Add a pygmentize lexer for Dedukti

### PR DESCRIPTION
**Pull request by francoisthire**
Add a file `tool/dedukti.py` that can be used with the LaTeX package `minted`.

### CODE REVIEW

**Comment by fblanqui** [comment]
Hi François. Thank you very much! Could you please add some sample Latex file to test your script?

**Comment by francoisthire** [comment]
Which folder should I use for that?

**Comment by rlepigre** [comment]
Just create a directory `tools/latex_minted`. Ideally, it would be great to have a `.sty` defining a new environment so that we can do
```latex
\begin{dedukti}
...
\end{dedukti}
```
And similarly with `lambdapi`.

**Comment by francoisthire** [comment]
I tried something, let me know if this is what you expect.

**Comment by rlepigre** [comment]
Just put all files in the `tools/latex_minted` directory, and that will be perfect. We can add a Lambdapi syntax later. And you can also remove the dedukti file, since its contents is in the tex fil already.

**Comment by francoisthire** [comment]
That should be it.

**Pull request merged**
