### PR TITLE
Use Github action for CI

### LINKED ISSUE #478: Migrate continuous integration
Some problem arise from the use of Travis (see #473). It seems we should change the continuous integration system. The alternatives seem to be either github actions, or an inria based ci.

### PR DESCRIPTION
**Pull request by vblot**
This is a CI script using github actions. The tests are performed against several ocaml versions and the `.opam` directory is cached to speed up the process. Should fix #478 .

### CODE REVIEW

**Comment by fblanqui** [comment]
Thanks @vblot ! Don't we need to remove the file .travis.yml?

**Comment by vblot** [comment]
I don't know, what is/was its use?

**Comment by fblanqui** [comment]
This file was used for CI on Travis.

**Comment by fblanqui** [comment]
Is it possible to automatically have links from the PR pages to the results of CI?
Currently, these links point to Travis. For instance, on https://github.com/Deducteam/lambdapi/pull/521 (the current PR), if you click on "Show all checks", you will see a link to Travis.
In addition, if you look at the commits on a branch, for instance on https://github.com/Deducteam/lambdapi/pulls, https://github.com/Deducteam/lambdapi/commits/master or https://github.com/Deducteam/lambdapi/pull/518/commits, there is a green tick if CI worked or a red cross if CI failed.

**Comment by vblot** [comment]
Has the corresponding part on travis been deleted as well?

**Comment by fblanqui** [comment]
Currently, there is a wekhook to Travis: https://github.com/Deducteam/lambdapi/settings/hooks
And there is currently nothing on https://github.com/Deducteam/lambdapi/actions/new

**Comment by vblot** [comment]
Ok so I suppose we can remove the webhook to travis, right? For your other question: I think these links will be generated as soon as the PR is merged. Indeed, they appear on my clone: https://github.com/vblot/lambdapi.

**Comment by fblanqui** [comment]
Hopefully. But wait that we merge #516 et #518 before removing travis webhook.

**Comment by vblot** [comment]
Ok I suppose the new CI checks will just be added to the existing travis check as soon as this is merged.

**Comment by vblot** [comment]
But if we include deletion of .travis.yml in this PR, then we would need to wait until we are ready to get rid of travis before merging.
So we have 2 options:
- we do not delete .travis.yml in this PR, so we can merge it now,
- we delete .travis.yml in this PR, but we have to wait for #516 and #518 to be merged before merging the current PR.
What do you want to do?

**Comment by fblanqui** [comment]
If there are no other remarks, I propose to merge this PR as it is.

**Comment by amelieled** [comment]
As @vblot said, we can delete travis file, right?

**Comment by fblanqui** [comment]
Right. @vblot do you mind to update your PR?

**Comment by vblot** [comment]
Since #516 and #518 are merged, I suppose so, yes.

**Comment by vblot** [comment]
Done.

**Comment by fblanqui** [comment]
Thanks @vblot !

**Comment by vblot** [comment]
Welcome, let's see how it goes in the long term.

**Comment by fblanqui** [comment]
Results are available on https://github.com/Deducteam/lambdapi/actions . We should probably remove the webhook to Travis now, right?

**Comment by vblot** [comment]
Yes, indeed.

**Comment by fblanqui** [comment]
Problem: there is no action generated when @gabrielhdt pushes on https://github.com/Deducteam/lambdapi/pull/535...

**Comment by fblanqui** [comment]
@vblot The current workflow is: `on: [push, workflow_dispatch]`. Shouldn't we add something else here to check every new commit in PRs?

**Comment by vblot** [comment]
I think you're right, it should be `on: [push, workflow_dispatch, pull_request]`, see https://docs.github.com/en/actions/reference/events-that-trigger-workflows.

**Comment by fblanqui** [comment]
Perhaps we should restrict to a few types only?
```
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
```

**Comment by vblot** [comment]
Yes that's probably more reasonable indeed.

**Comment by fblanqui** [comment]
So, we should have something like:
```
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  push:
  worklow_dispatch:
```
I am not sure about the syntax. Do you mind to make a PR to fix the workflow script?

**Comment by vblot** [comment]
Actually the default is only `types: [opened, synchronize, reopened]`:
```
Note: By default, a workflow only runs when a pull_request's activity type is opened, synchronize, or reopened. To trigger workflows for more activity types, use the types keyword.
```
but as you suggest it's probably better to have it also on edits, I think.

**Comment by vblot** [comment]
Here it is: #537.

**Comment by fblanqui** [comment]
FYI I just deactivated (not deleted) the Travis webhook.

**Comment by amelieled** [comment]
But Travis is always expected as you can see in PR #530

**Comment by vblot** [comment]
I think this is because this particular CI was triggered before the removal of `.travis.yml`.

**Comment by amelieled** [comment]
Frédéric just opened a new PR (#541 ) and there is the same thing.

**Comment by vblot** [comment]
My guess is that it's because `.travis.yml` was present at the forking point of #541 (which is fdbd9bbfb97f8ef7d38d78254d515979c8d8308f). We could try opening a PR from a fork point that is beyond 8ee26bb7268a8092162ca4046febfaf4c64c2299 if we want to be sure.

**Comment by amelieled** [comment]
Yes I do it (See #542 ) but same problem.

**Comment by amelieled** [comment]
Maybe the answer is here: https://github.com/travis-ci/travis-ci/issues/8988
Good luck!

**Comment by vblot** [comment]
Nice catch, that was it!

**Comment by fblanqui** [comment]
Thanks @amelieled !

**Comment by amelieled** [comment]
And thanks @vblot ! :)
Bye bye Travis ! :)

**Pull request merged**
