### PR TITLE
[WIP] Switch from Earley to Pacomb

### PR DESCRIPTION
**Pull request by rlepigre**
This is going to address several issues, including #300 and #305 (we should release once this is merged I think). Parsing performance should also improve significantly.

**Note:** this PR can only be merged once @craff has published a first stable version of Pacomb.

### CODE REVIEW

**Comment by rlepigre** [comment]
Note that CI is failing on 4.09.0 since `why3.1.2.0` is incompatible with this version. For now we cannot use `why3.1.3.0` due to a bug that I reported (see [here](https://gitlab.inria.fr/why3/why3/issues/463)) and which has now been fixed. However, we will have to wait for the release of `why3.1.3.1`.

**Comment by fblanqui** [comment]
Why3 version 1.3.1 has been released. @rlepigre When do you think you will be able to merge this PR more or less? Is it a matter of days, weeks or months?

**Comment by rlepigre** [comment]
> Why3 version 1.3.1 has been released. @rlepigre When do you think you will be able to merge this PR more or less? Is it a matter of days, weeks or months?

Yeah, I fixed that in `master` already. I would say it is a matter of weeks. This PR needs to be rewritten from scratch, it cannot be rebased in its current state (early commits only work with old versions of `pacomb` that are not referenced anywhere). It should be relatively easy for me to do so, and to talk with Christophe to see when he plans to release `pacomb`. I think he expected some of you in Deducteam to run benchmarks, or at least to tell him how to run them. But I am gonna have a look myself when I have a moment.

I think it is best to wait for this branch to be merged before issuing a release of Lambdapi. Many features need more testing anyway.

**Comment by fblanqui** [comment]
I close this PR as it is subsumed by https://github.com/Deducteam/lambdapi/pull/441 and thus won't be merged anymore.

**Pull request closed without merging**
