### PR TITLE
[lsp] Improve proof and goal display.

### PR DESCRIPTION
**Pull request by ejgallego**
Thanks to recent improvements. `theorem` is green if the statement
typechecks, `qed` is green when the proof has been finished.

### CODE REVIEW

**Comment by rlepigre** [comment]
Stupid question: is there any way to display the goal using the Emacs mode?

**Comment by ejgallego** [comment]
> Stupid question: is there any way to display the goal using the Emacs mode?

Not as of today; `eglot` doesn't like non-standard fields in the diagnostics.

We could either:
- use the more complete `emacs-lsp` mode and add support for the goals field;
- add goal information to hover

That second choice is fairly easy to do although not optimal.

**Comment by rlepigre** [comment]
Maybe we should use the second option as a first step then. That is clearly not great, but that's a start. Did you manage to get Atom to work again?

**Comment by ejgallego** [comment]
Indeed atom does work now; however I don't see the goals [they are sent but atom doesn't print them]

It must be something trivial but I won't have time to look at Atom today.

**Comment by rlepigre** [comment]
OK. I personally don't think that Atom is worth fixing, especially if it is gonna die soon. I guess it is more important to have some support for emacs, even if it is only through hover.

**Pull request merged**
