### PR TITLE
doc: create a file for each editor

### PR DESCRIPTION
**Pull request by fblanqui**

### CODE REVIEW

**Comment by fblanqui** [comment]
Can be visualized on https://github.com/fblanqui/lambdapi/blob/uidoc/doc/DOCUMENTATION.md

**Comment by fblanqui** [comment]
@gabrielhdt About Vim: is it still the case that the user has to do make install_vim when installing LP with opam? See https://github.com/fblanqui/lambdapi/blob/uidoc/doc/vim.md

**Comment by gabrielhdt** [comment]
> @gabrielhdt About Vim: is it still the case that the user has to do make install_vim when installing LP with opam? See https://github.com/fblanqui/lambdapi/blob/uidoc/doc/vim.md

The user has to `make install_vim`, because vim files are not handled by dune. But after #416 and #411, I think that using dune for everything is not a good idea, and I suggest going back to Makefile targets.

**Comment by fblanqui** [comment]
The inconvenient is that you need the sources. Can't we have opam packages "lambdapi-emacs" and "lambdapi-vim" just for the emacs/vim modes?

**Comment by gabrielhdt** [comment]
It would be strange, opam is made to install ocaml packages, not emacs lisp ones... all this would make things confusing, imo.

I don't understand what you mean by "you need the sources", to do what? And when did we not need the sources?

**Pull request merged**
