### PR TITLE
assume tactic with no identifiers

### PR DESCRIPTION
**Pull request by gabrielhdt**
Assume as many hypotheses as can be.

### CODE REVIEW

**Comment by fblanqui** [comment]
Hi @gabrielhdt . The problem with this kind of tactics is that this is not very robust because it introduces many hypotheses not named by the user. This is not very good practice. So I would prefer not to add such a tactic.

**Comment by gabrielhdt** [comment]
I see the point, but it's very handy for prototyping: propositions may almost be solved automatically using `assume; why3;`.

**Comment by fblanqui** [comment]
assume shouldn't be needed before why3, that is, there should be no difference between assume;why3 and why3. This is perhaps not the case now but this should be fixed.

**Comment by gabrielhdt** [comment]
Superseded by #765

**Pull request closed without merging**
