### PR TITLE
Emacs fixes

### LINKED ISSUE #349: Emacs mode: indentation missing in a proof

### PR DESCRIPTION
**Pull request by gabrielhdt**
Fixes #349, and company setup

### CODE REVIEW

**Comment by gabrielhdt** [comment]
Yes it is. But there might be conflicts with master.

**Comment by rlepigre** [comment]
OK, can you rebase?

**Comment by rlepigre** [comment]
It seems you did something weird (applying patches several times and all). I rebase and force-pushed. Can you quickly check that everything is alright before I merge @gabrielhdt?

**Comment by gabrielhdt** [comment]
Actually, I'll integrate MELPA comments into this pull request
<https://github.com/melpa/melpa/pull/6827>.

And @rlepigre, @fblanqui, do you have an idea regarding coding conventions for Lambdapi, and particularly the indentation?

**Comment by rlepigre** [comment]
I guess indentation should somehow agree with the output of the `lambdpi beautify` command. But the pretty-pinter might not do the best possible job yet.

**Comment by gabrielhdt** [comment]
Finally, we can merge this now. 
* Melpa developers are taking their time, so I'll likely be opening a new PR once I have their feedback; 
* I have let mistakes slip through #356 (which are fixed here); 
* and I have improved the indentation engine more than I thought. It should be more consistent, more flexible (not confused by declared symbols), and keener on CPU usage.

**Comment by gabrielhdt** [comment]
... I think you can merge...

**Pull request merged**
