### PR TITLE
Updating pratter

### PR DESCRIPTION
**Pull request by gabrielhdt**
To be merged once pratter 2.0.0 is available on opam.

### CODE REVIEW

**Comment by fblanqui** [comment]
This PR needs to be updated. What changes in this new version of Pratter?

**Comment by gabrielhdt** [comment]
Pratter 2 has a slightly new api, and postfix operators.

**Comment by fblanqui** [comment]
Great. Could you please add a test file with a postfix operator, for instance ! for factorial. You can also change group.lp by replacing inv by ^-1 (in unicode).

**Comment by fblanqui** [comment]
This PR will fix #827 .

**Comment by fblanqui** [comment]
Please update CHANGES too.

**Pull request merged**
