### PR TITLE
Update documentation and VSCode package

### LINKED ISSUE #761: The vscode API needs to be updated
See https://github.com/microsoft/vscode/issues/136964. If some files are changed, update docs/structure.rst as well.

### PR DESCRIPTION
**Pull request by fblanqui**
fix #761

### CODE REVIEW

**Comment by fblanqui** [comment]
Hi @firewall2142 . Do we still need to keep a local copy vscode.d.ts ?

**Comment by firewall2142** [comment]
No, we don't need it

**Comment by fblanqui** [comment]
@firewall2142 How to do this? Other question: would it be possible to put our extension on the vscode marketplace?

**Comment by firewall2142** [comment]
Extension works fine after deleting it. I can't find anything in docs about this file being necessary.

Yes : https://code.visualstudio.com/api/working-with-extensions/publishing-extension

**Pull request merged**
