### PR TITLE
fix Sig_state.of_sign

### LINKED ISSUE #778: Documentation of `of_sign` function
If I'm correct, `Sig_state.of_sign s` *does not* open signature `s` in the resulting state. This should be documented.

### PR DESCRIPTION
**Pull request by fblanqui**
fix  #778

### CODE REVIEW

**Review by gabrielhdt — COMMENTED** [review]
I think it would be nice to add unit tests to test  that signatures are not opened. for instance,
```diff
diff --git a/tests/dune
 b/tests/dune
index 3d1bf8bf..ce553086 100644
--- a/tests/dune
+++ b/tests/dune
@@ -1,5 +1,5 @@
 (tests
- (names ok_ko rewriting purity)
+ (names ok_ko rewriting purity kernel)
  (deps
   (glob_files OK/*.lp)
   (glob_files OK/*.dk)
diff --git a/tests/kernel.ml b/tests/kernel.ml
new file mode 100644
index 00000000..722d9a81
--- /dev/null
+++ b/tests/kernel.ml
@@ -0,0 +1,45 @@
+open Common
+open Core
+
+let () =
+  (* Set library root to avoid creating files out of the sandbox when opam runs
+     tests. *)
+  Library.set_lib_root (Some (Sys.getcwd ()))
+
+let not_opened_sign () =
+  let sign = Sig_state.create_sign [ "dummy" ] in
+  let _ =
+    Sign.add_symbol sign Term.Public Term.Defin Term.Eager false
+      (Pos.none "foo") Term.mk_Type []
+  in
+  let ss = Sig_state.of_sign sign in
+  Alcotest.(check unit)
+    "find_sym fails"
+    ( try
+        ignore
+        @@ Sig_state.find_sym ~prt:true ~prv:true ss (Pos.none ([], "foo"))
+      with Error.Fatal (_, _) -> () )
+    ()
+
+let open_sign () =
+  let sign = Sig_state.create_sign [ "dummy" ] in
+  let _ =
+    Sign.add_symbol sign Term.Public Term.Defin Term.Eager false
+      (Pos.none "foo") Term.mk_Type []
+  in
+  let ss = Sig_state.of_sign sign in
+  let ss = Sig_state.open_sign ss sign in
+  Alcotest.(check unit)
+    "find_sym succeeds"
+    (ignore @@ Sig_state.find_sym ~prt:true ~prv:true ss (Pos.none ([], "foo")))
+    ()
+
+let () =
+  let open Alcotest in
+  run "Kernel"
+    [ ( "Signatures management"
+      , [ test_case "Signature not opened upon signature state creation" `Quick
+            not_opened_sign
+        ; test_case "Opening signature in signature state" `Quick open_sign
+        ] )
+    ]

```

**Comment by fblanqui** [comment]
@gabrielhdt Do you have more comments?

**Comment by gabrielhdt** [comment]
> @gabrielhdt Do you have more comments?

No I don't.

**Comment by fblanqui** [comment]
In fact, this PR was kind of wrong. I am going to revert it in https://github.com/Deducteam/lambdapi/pull/792.

**Comment by gabrielhdt** [comment]
I was expecting to see how it behaves in the long run. Anyway it would have been a better idea to adapt the tests than remove them.

**Comment by fblanqui** [comment]
Perhaps but it didn't have the time for this. Anyway, it will be better in a separate PR.

**Pull request merged**
