### PR TITLE
remove set keyword

### PR DESCRIPTION
**Pull request by fblanqui**

### CODE REVIEW

**Comment by fblanqui** [comment]
Any comment on this PR ?

**Comment by gabrielhdt** [comment]
You may want edit the vim syntax file as well.

**Comment by amelieled** [comment]
I have a question: why change the syntax again? It's annoying for other works, and not really change important thing for you.

**Comment by fblanqui** [comment]
@gabrielhdt the vim mode does not handle multi-lines comments. Do you want to fix it? (no need)

**Pull request merged**
