### PR TITLE
[lsp] Fix processing of proofs.

### PR DESCRIPTION
**Pull request by ejgallego**
There are some remaining problems tho, but they should be easy to fix:

- No way to get the goals from a proof state.
- `Pure.end_proof` produces an exception instead of returning a more
  informative result.

Tested with emacs, seems to work modulo the problems with the exceptions in `end_proof`.

### CODE REVIEW

**Comment by ejgallego** [comment]
Ok, this is ready to merge despite the problem with the highlighting of `end_proof`. Actually I'd be cool if the AST provided some extra locations for:
```
theorem foo : B ⇒ B
proof
   tacs...
qed
```
I'd be great to get the location of `qed` and of `theorem foo : .... proof` as to provide good highlighting.

**Comment by rlepigre** [comment]
Thanks @ejgallego, I'll merge and see what I can do to fix the remaining issues tomorrow!

**Comment by rlepigre** [comment]
@ejgallego positions are now available for the theorem statement and for the terminator (using functions taking as input a proof state). I also fixed the problem with the exception. I'll take care of the missing things later.

**Comment by ejgallego** [comment]
Looks good thanks!

**Comment by rlepigre** [comment]
@ejgallego: I added a function te extract goals from the proof state in 17780d2cfdb1a8b65289e4112398c99edb3d43d5. You can have a look at the implementation of `Proof.pp` to see how to extract the relevant data. Alternatively, I could give you a function with type `proof_state -> ((string * term) * term) list` if you prefer.

**Comment by ejgallego** [comment]
It is good like this, thanks!

**Pull request merged**
