### PR TITLE
add example with focus and adapt emacs mode

### PR DESCRIPTION
**Pull request by Rehan-MALAK**

### CODE REVIEW

**Comment by Rehan-MALAK** [comment]
Are the emacs constant ``lambdapi--tactics`` in editors/emacs/lambdapi-smie.el and editors/emacs/lambdapi-vars.el supposed to be equal ?

**Comment by gabrielhdt** [comment]
> Are the emacs constant `lambdapi--tactics` in editors/emacs/lambdapi-smie.el and editors/emacs/lambdapi-vars.el supposed to be equal ?

Yes, you can remove the value from `lambdapi-smie.el`.

**Comment by gabrielhdt** [comment]
https://github.com/Deducteam/lambdapi/blob/6a365ab4b9188514ad60ba4b665cdcccc0e540e9/editors/emacs/lambdapi-smie.el#L24
Make  sure you change this line to use `lambdapi-tactics` from `lambdapi-vars.el`

**Comment by fblanqui** [comment]
Can this PR be merged? If yes, thanks to update.

**Comment by Rehan-MALAK** [comment]
> https://github.com/Deducteam/lambdapi/blob/6a365ab4b9188514ad60ba4b665cdcccc0e540e9/editors/emacs/lambdapi-smie.el#L24
> 
> Make sure you change this line to use `lambdapi-tactics` from `lambdapi-vars.el`

@gabrielhdt
do you mean just replace ``lambdapi--tactics`` with ``lambdapi-tactics`` ? (and if yes, can we change all the "double dash" names with "single dash" ones ?)

**Comment by gabrielhdt** [comment]
> > https://github.com/Deducteam/lambdapi/blob/6a365ab4b9188514ad60ba4b665cdcccc0e540e9/editors/emacs/lambdapi-smie.el#L24
> > 
> > Make sure you change this line to use `lambdapi-tactics` from `lambdapi-vars.el`
> 
> @gabrielhdt
> do you mean just replace `lambdapi--tactics` with `lambdapi-tactics` ? (and if yes, can we change all the "double dash" names with "single dash" ones ?)

IIRC, we use double dashes for private variables, and simple dashes for variables that should be exposed to emacs, see <https://github.com/bbatsov/emacs-lisp-style-guide#naming>. Here we may use the double dashes everywhere.

**Comment by Rehan-MALAK** [comment]
@gabrielhdt
so this double dash thing is just coding style but it doesn't change anything in the scoping side, right ?

I applied this in a naive way for all the defun / defconst / defvar  

```bash
sed -i 's/defun lambdapi-\([a-z]\)/defun lambdapi--\1/g' editors/emacs/*.el
for fun in local-abbrev abbrev-setup capf-setup completion-at-point update-line-number create-goals-buffer ; do
  sed -i "s/lambdapi-$fun/lambdapi--$fun/g" editors/emacs/*.el
done

sed -i 's/defconst lambdapi-\([a-z]\)/defconst lambdapi--\1/g' editors/emacs/*.el
for const in legacy-font-lock-keywords font-lock-keywords tactics sig-commands warning misc-commands misc-keywords ; do
  sed -i "s/lambdapi-$const/lambdapi--$const/g" editors/emacs/*.el
done
 
sed -i 's/defvar lambdapi-\([a-z]\)/defvar lambdapi--\1/g' editors/emacs/*.el
for var in mode-legacy-syntax-table current-line-number changed-line-hook syntax-table mode-map unicode-prefer-company ; do
  sed -i "s/lambdapi-$var/lambdapi--$var/g" editors/emacs/*.el
done
```

but not sure what should be done here

**Comment by gabrielhdt** [comment]
@Rehan-MALAK I don't remember if it changes scoping, but your script is too aggressive because we have things that must be exposed to emacs, such as `lambdapi-unicode-prefer-company`.

**Comment by fblanqui** [comment]
@Rehan-MALAK can we merge this PR after update?

**Comment by fblanqui** [comment]
Hi @Rehan-MALAK and happy new year! After all the changes that have been done in the emacs code, what should we do with this PR? @firewall2142 do you see anything that should be included in your next PR on emacs?

**Comment by firewall2142** [comment]
> @firewall2142 do you see anything that should be included in your next PR on emacs?

If you're talking about changes I need to make to my PR if this gets merged, then no (or atleast not very much).

**Comment by fblanqui** [comment]
Ok. Then, we can probably close this PR as it won't be merged.

**Pull request closed without merging**
