### PR TITLE
fix issue #226

### PR DESCRIPTION
**Pull request by fblanqui**

### CODE REVIEW

**Comment by francoisthire** [comment]
Don't we need just to sanitize names when there is a conflict? Sanitization may need to keep a list of identifiers already saw though.

**Comment by rlepigre** [comment]
> Don't we need just to sanitize names when there is a conflict? Sanitization may need to keep a list of identifiers already saw though.

I'd prefer not to have to do that. Seriously, we don't translate that many things from the old syntax to the new one anyway. On thing we could do though, is fail on printing if we find a keyword. That way you know that you need to rename stuff in the original file before translating, and the target of the translation is always correct.

**Comment by fblanqui** [comment]
About {|...|} in DK: this is another example showing that this is really annoying to keep adding features to DK!!!

**Comment by fblanqui** [comment]
Ok for failing. After all, this is not the job of LP to take care/rename names!

**Comment by fblanqui** [comment]
So, we could close this PR and the corresponding issue (won't fix)?

**Comment by rlepigre** [comment]
Yes, I guess so. But what you did in this PR is a good start. I'll add a couple of comments with things for you to change.

**Comment by rlepigre** [comment]
Actually let's close that. I'll take care of the change it is going to be faster.

**Comment by fblanqui** [comment]
You can push to my branch now if you want.

**Comment by rlepigre** [comment]
I'll push on master when I'm done, I just realized that there is a little problem with module paths.

**Pull request closed without merging**
