### PR TITLE
Rectools

### PR DESCRIPTION
**Pull request by gabrielhdt**
This pull request provides a script to measure the performance of the rewriting engine against CafeOBJ, Maude, ocaml (compiled and interpreted) and haskell (compiled and interpreted).

The engines are compared on the REC examples which do not involve conditional rewriting.

The haskell and ocaml computations have been tested and work, the cafeobj hasn't been.

The script produces a csv file, which renders in LaTeX:
2020-04-23-111923_533x841_scrot

### CODE REVIEW

**Comment by fblanqui** [comment]
Thanks Gabriel. Would it be possible to extend this script with Maude?

**Comment by gabrielhdt** [comment]
Ah yes indeed.

**Comment by fblanqui** [comment]
@gabrielhdt what is the status of this PR?

**Comment by gabrielhdt** [comment]
I think we can merge it. Let me just merge the master branch.

**Comment by fblanqui** [comment]
@gabrielhdt thanks to let me know when we can merge

**Comment by gabrielhdt** [comment]
We can merge!

**Comment by fblanqui** [comment]
Thanks @gabrielhdt !

**Pull request merged**
